<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pendaftar extends Model
{
    use HasFactory;
    public $timestamps = false;
    public $table = "pendaftar";
    protected $fillable = [
        'nomor',
        'ummb',
        'jurusan',
        'program',
        'nodaftar',
        'nama',
        'agama',
        'sex',
        'alamat',
        'telp',
        'status',
        'spi',
        'nrp',
        'tahun_ajaran',
        'semester',
        'warga',
        'tgllahir',
        'penghasilan',
        'jumlah_anak',
        'el',
        'pmdk',
        'anak_ke',
        'gelombang',
        'bebas_spp',
        'bebas_ikoma',
        'bebas_kemahasiswaan',
        'bebas_spi',
        'keterangan_bebas_spi',
        'tempat_lahir',
        'smu',
        'alamat_smu',
        'tahun_lulus_smu',
        'nilai_ijazah',
        'nilai_uan',
        'darah',
        'prestasi_olahraga',
        'nun',
        'nijazah',
        'ayah',
        'kerja_ayah',
        'ibu',
        'kerja_ibu',
        'keterangan_ibu',
        'penghasilan_ibu',
        'alamat_ortu',
        'notelp_ortu',
        'nisn',
        'tanggal_ubah',
        'cadangan',
        'ukt',
        'bebas_ukt',
        'sekolah',
        'kode_transaksi',
        'publik',
        'mahasiswa_jalur_penerimaan',
        'kota',
        'kota_ortu',
        'pendaftaran',
        'ikoma',
        'kemahasiswaan',
        'subkampus',
        'foto',
        'tanggal_transfer_spp',
        'kirim_email',
        'kirim_sms',
        'email',
        'nik',
        'kelas_pagi_sore',
        'ijasah',
        'status_kawin',
        'ukuran_baju',
        'pernahpt',
        'tahunmasuk_pt',
        'jumlah_sks',
        'pt_asal',
        'nunmapel',
        'nijazahmapel',
        'status_smu',
        'jurusan_smu',
        'thlahirayah',
        'pendidikanayah',
        'thlahiribu',
        'pendidikanibu',
        'sumberbiaya',
        'lembaga',
        'jenis_lembaga',
        'jenis_tempattinggal',
        'transportasi',
        'minat',
        'infopolije',
        'biaya_lain',
        'ukt3',
        'ukt4',
        'ukt5',
        'kelurahan',
        'kecamatan',
        'feeder_wilayah',
        'nomor_ukt',
        'bidikmisi',
        'rata_sem_1',
        'rata_sem_2',
        'rata_sem_3',
        'rata_sem_4',
        'rata_sem_5',
        'rata_sem_6',
        'kap_bidikmisi',
        'noref_bank',
        'tanggal_transfer',
        'pembayaran',
        'scan_pembayaran',
        'jurusan_asal',
        'prestasi',

    ];
}
